/**
 * Synthetic CRC / OS / GHL / DF catalogs for dry-run and tests.
 * No real client PII. Real CRC exports must stay in local/crc-exports/ (gitignored).
 */

import type { CrcExportFile, IdentityCatalog } from "./types";

export const SYNTHETIC_NOW = "2026-08-16T00:00:00.000Z";
export const SYNTHETIC_NOW_MS = Date.parse(SYNTHETIC_NOW);

export const SYNTHETIC_CRC_EXPORT: CrcExportFile = {
  sourceSystem: "CREDIT_REPAIR_CLOUD",
  synthetic: true,
  exportedAt: SYNTHETIC_NOW,
  clients: [
    {
      crcClientId: "CRC-SYN-1001",
      grantsClientId: "GC-SYN-000001",
      ghlContactId: "ghl_syn_1001",
      disputeFoxClientId: "df_syn_1001",
      smartCreditId: "sc_syn_1001",
      firstName: "Alex",
      lastName: "Rivera",
      email: "alex.rivera@example.test",
      emailVerified: true,
      emailVerifiedAt: "2026-07-01T00:00:00.000Z",
      phone: "5550101001",
      phoneVerified: true,
      status: "verified_active",
      verifiedActive: true,
      currentlyProcessing: true,
      lastWorkedAt: "2026-08-10T00:00:00.000Z",
      lastReportAt: "2026-08-01T00:00:00.000Z",
      lastDisputeAt: "2026-08-05T00:00:00.000Z",
    },
    {
      crcClientId: "CRC-SYN-1002",
      firstName: "Blair",
      lastName: "Chen",
      email: "blair.chen@example.test",
      emailVerified: true,
      phone: "5550101002",
      phoneVerified: true,
      status: "inactive",
      lastWorkedAt: "2023-02-01T00:00:00.000Z",
    },
    {
      crcClientId: "CRC-SYN-1003",
      ghlContactId: "ghl_syn_1003",
      firstName: "Casey",
      lastName: "Ortiz",
      email: "casey.ortiz@example.test",
      emailVerified: true,
      phone: "5550101003",
      phoneVerified: true,
      status: "active",
      currentlyProcessing: true,
      lastWorkedAt: "2026-08-06T00:00:00.000Z",
    },
    {
      crcClientId: "CRC-SYN-1004",
      firstName: "Dana",
      lastName: "Kim",
      email: "dana.kim@example.test",
      emailVerified: true,
      phone: "5550101004",
      phoneVerified: true,
      status: "inactive",
      lastWorkedAt: "2022-11-15T00:00:00.000Z",
    },
    {
      crcClientId: "CRC-SYN-1005",
      firstName: "Ellis",
      lastName: "Stone",
      address: { line1: "100 Example Ave", city: "Springfield", state: "IL", postalCode: "62701" },
      addressVerified: true,
      status: "inactive",
      lastWorkedAt: "2024-01-01T00:00:00.000Z",
    },
    {
      crcClientId: "CRC-SYN-1006",
      firstName: "Fran",
      lastName: "Wells",
      phone: "5550101999",
      phoneVerified: true,
      status: "inactive",
      lastWorkedAt: "2023-08-01T00:00:00.000Z",
    },
    {
      crcClientId: "CRC-SYN-1008",
      ghlContactId: "ghl_syn_1008",
      firstName: "Gray",
      lastName: "Holt",
      email: "gray.holt@example.test",
      emailVerified: true,
      status: "closed",
      doNotReactivate: true,
      lastWorkedAt: "2021-05-01T00:00:00.000Z",
    },
    {
      crcClientId: "CRC-SYN-1009",
      ghlContactId: "ghl_syn_1009",
      disputeFoxClientId: "df_syn_1009",
      firstName: "Harper",
      lastName: "Ives",
      email: "harper.ives@example.test",
      emailVerified: true,
      phone: "5550101009",
      phoneVerified: true,
      phoneVerifiedAt: "2024-06-01T00:00:00.000Z",
      address: { line1: "9 Test Lane", city: "Atlanta", state: "GA", postalCode: "30301" },
      addressVerified: true,
      addressVerifiedAt: "2024-06-01T00:00:00.000Z",
      status: "inactive",
      lastWorkedAt: "2024-06-01T00:00:00.000Z",
    },
    {
      crcClientId: "CRC-SYN-1010",
      firstName: "Indigo",
      lastName: "Jones",
      email: "indigo.jones.old@example.test",
      emailVerified: true,
      emailVerifiedAt: "2023-01-01T00:00:00.000Z",
      phone: "5550101010",
      phoneVerified: true,
      status: "inactive",
      lastWorkedAt: "2023-01-01T00:00:00.000Z",
    },
    {
      crcClientId: "CRC-SYN-1011",
      smartCreditId: "sc_syn_1011",
      firstName: "Jules",
      lastName: "Park",
      email: "jules.park.crc@example.test",
      emailVerified: true,
      status: "inactive",
      lastWorkedAt: "2023-09-01T00:00:00.000Z",
    },
    {
      crcClientId: "CRC-SYN-1012",
      firstName: "Kai",
      lastName: "Quinn",
      email: "kai.quinn@example.test",
      emailVerified: true,
      status: "inactive",
      lastWorkedAt: "2024-02-01T00:00:00.000Z",
      documents: [
        {
          id: "CRC-DOC-SYN-1",
          crcClientId: "CRC-SYN-1012",
          documentType: "CREDIT_REPORT",
          originalDate: "2024-03-01",
          storageHint: "secure-storage://crc/CRC-SYN-1012/credit-report",
          rawIncluded: false,
        },
        {
          id: "CRC-DOC-SYN-2",
          crcClientId: "CRC-SYN-1012",
          documentType: "IDENTIFICATION",
          originalDate: "2023-12-15",
          storageHint: "secure-storage://crc/CRC-SYN-1012/identification",
          rawIncluded: false,
        },
      ],
    },
    {
      crcClientId: "CRC-SYN-1013",
      firstName: "Lane",
      lastName: "Reed",
      email: "lane.reed.crc@example.test",
      emailVerified: true,
      status: "inactive",
      lastWorkedAt: "2022-04-01T00:00:00.000Z",
    },
    {
      crcClientId: "CRC-SYN-1014",
      firstName: "Mina",
      lastName: "Shaw",
      email: "mina.shaw.other@example.test",
      emailVerified: true,
      status: "inactive",
      lastWorkedAt: "2023-07-01T00:00:00.000Z",
    },
    {
      crcClientId: "CRC-SYN-1015",
      ghlContactId: "ghl_syn_1015",
      firstName: "Nico",
      lastName: "Vale",
      email: "nico.vale@example.test",
      emailVerified: true,
      status: "inactive",
      lastWorkedAt: "2023-03-01T00:00:00.000Z",
    },
  ],
};

// Remove accidental extra field if I added one - I'll fix 1014
export const SYNTHETIC_OS_CATALOG: IdentityCatalog["osMasters"] = [
  {
    grantsClientId: "GC-SYN-000001",
    firstName: "Alex",
    lastName: "Rivera",
    email: "alex.rivera@example.test",
    emailVerified: true,
    emailVerifiedAt: "2026-07-01T00:00:00.000Z",
    phone: "5550101001",
    phoneVerified: true,
    crcClientId: "CRC-SYN-1001",
    ghlContactId: "ghl_syn_1001",
    disputeFoxClientId: "df_syn_1001",
    smartCreditId: "sc_syn_1001",
  },
  {
    grantsClientId: "GC-SYN-000002",
    firstName: "Blair",
    lastName: "Chen",
    email: "blair.chen@example.test",
    emailVerified: true,
    phone: "5550101002",
    phoneVerified: true,
  },
  {
    grantsClientId: "GC-SYN-000003",
    firstName: "Casey",
    lastName: "Ortiz",
    email: "casey.ortiz@example.test",
    emailVerified: true,
    phone: "5550101003",
    phoneVerified: true,
    ghlContactId: "ghl_syn_1003",
  },
  {
    grantsClientId: "GC-SYN-000005",
    firstName: "Ellis",
    lastName: "Stone",
    email: "ellis.stone.os@example.test",
    emailVerified: true,
    address: { line1: "100 Example Ave", city: "Springfield", state: "IL", postalCode: "62701" },
    addressVerified: true,
  },
  {
    grantsClientId: "GC-SYN-000006A",
    firstName: "Jordan",
    lastName: "Wells",
    email: "jordan.wells@example.test",
    emailVerified: true,
    phone: "5550101999",
    phoneVerified: true,
  },
  {
    grantsClientId: "GC-SYN-000006B",
    firstName: "Morgan",
    lastName: "Wells",
    email: "morgan.wells@example.test",
    emailVerified: true,
    phone: "5550101999",
    phoneVerified: true,
  },
  {
    grantsClientId: "GC-SYN-000008",
    firstName: "Gray",
    lastName: "Holt",
    email: "gray.holt@example.test",
    emailVerified: true,
    ghlContactId: "ghl_syn_1008",
  },
  {
    grantsClientId: "GC-SYN-000009",
    firstName: "Harper",
    lastName: "Ives",
    email: "harper.ives@example.test",
    emailVerified: true,
    emailVerifiedAt: "2026-01-15T00:00:00.000Z",
    phone: null,
    ghlContactId: "ghl_syn_1009",
    disputeFoxClientId: "df_syn_1009",
  },
  {
    grantsClientId: "GC-SYN-000010",
    firstName: "Indigo",
    lastName: "Jones",
    email: "indigo.jones@example.test",
    emailVerified: true,
    emailVerifiedAt: "2026-06-01T00:00:00.000Z",
    phone: "5550101010",
    phoneVerified: true,
  },
  {
    grantsClientId: "GC-SYN-000011",
    firstName: "Jules",
    lastName: "Park",
    email: "jules.park.os@example.test",
    emailVerified: true,
    smartCreditId: "sc_syn_1011",
  },
  {
    grantsClientId: "GC-SYN-000012",
    firstName: "Kai",
    lastName: "Quinn",
    email: "kai.quinn@example.test",
    emailVerified: true,
  },
  {
    grantsClientId: "GC-SYN-000013",
    firstName: "Lane",
    lastName: "Reed",
    email: "lane.reed.os@example.test",
    emailVerified: true,
    address: { line1: "77 Other Street", city: "Peoria", state: "IL", postalCode: "61602" },
    addressVerified: true,
  },
  {
    grantsClientId: "GC-SYN-000014",
    firstName: "Mina",
    lastName: "Shaw",
    email: "mina.shaw.os@example.test",
    emailVerified: true,
    crcClientId: "CRC-SYN-1014",
  },
];

export const SYNTHETIC_GHL_CATALOG: IdentityCatalog["ghlContacts"] = [
  {
    ghlContactId: "ghl_syn_1001",
    firstName: "Alex",
    lastName: "Rivera",
    email: "alex.rivera@example.test",
    phone: "5550101001",
    grantsClientId: "GC-SYN-000001",
    crcClientId: "CRC-SYN-1001",
    disputeFoxClientId: "df_syn_1001",
  },
  {
    ghlContactId: "ghl_syn_1003",
    firstName: "Casey",
    lastName: "Ortiz",
    email: "casey.ortiz@example.test",
    phone: "5550101003",
    grantsClientId: "GC-SYN-000003",
  },
  {
    ghlContactId: "ghl_syn_1008",
    firstName: "Gray",
    lastName: "Holt",
    email: "gray.holt@example.test",
    grantsClientId: "GC-SYN-000008",
  },
  {
    ghlContactId: "ghl_syn_1009",
    firstName: "Harper",
    lastName: "Ives",
    email: "harper.ives@example.test",
    grantsClientId: "GC-SYN-000009",
  },
  {
    ghlContactId: "ghl_syn_1015",
    firstName: "Nico",
    lastName: "Vale",
    email: "nico.vale@example.test",
  },
];

export const SYNTHETIC_DF_CATALOG: IdentityCatalog["dfClients"] = [
  {
    disputeFoxClientId: "df_syn_1001",
    firstName: "Alex",
    lastName: "Rivera",
    email: "alex.rivera@example.test",
    grantsClientId: "GC-SYN-000001",
    crcClientId: "CRC-SYN-1001",
    started: true,
    stage: "Round 1 Sent",
  },
  {
    disputeFoxClientId: "df_syn_1009",
    firstName: "Harper",
    lastName: "Ives",
    email: "harper.ives@example.test",
    grantsClientId: "GC-SYN-000009",
    started: true,
    stage: "Round 2 Ready",
  },
];

export function syntheticCatalog(): IdentityCatalog {
  return {
    osMasters: SYNTHETIC_OS_CATALOG,
    ghlContacts: SYNTHETIC_GHL_CATALOG,
    dfClients: SYNTHETIC_DF_CATALOG,
  };
}
